# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김도현
title: Backend Engineer
email: kdohyeon@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: kdohyeon.tistory.com
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: kdohyeon
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/kdohyeon.png
about_content: | # this will include new lines to allow paragraphs
  5년간 MSA 환경에서 Java & Spring, AWS 기반으로 리테일 비즈니스, MAU 200만 명품 패션 이커머스 등과 관련된 백엔드 서비스를 개발을 해왔으며, 
  상품 카탈로그, 리뷰, 전시 등 다양한 도메인에 대한 경험이 있습니다.
  
  `고객이 필요로 하는` 서비스를 개발하는 것이 중요하다는 생각에 데이터에 기반한 의사결정, UI/UX, 서비스 사용성 등에 대해 고민하며 업무를 수행합니다. 
  
  문서화의 힘을 믿고, 항상 살아있는 문서를 관리하기 위해 노력합니다.
  
  "배워서 남주자" 라는 말을 좋아해서 대학생들을 위한 특강, 스프링 온라인 강의를 진행해왔습니다.
  
  6년간 미국과 스웨덴에서 중, 고등학교를 다녔기에 다양한 문화를 이해하고 영어로 원활한 커뮤니케이션이 가능합니다. 

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: 트렌비 (Trenbe)
        sub_title: Backend Engineer
        caption: 2022. 03 ~ Present
        link: www.trenbe.com
        quote: >
          명품 패션 이커머스 서비스
        description: | # this will include new lines to allow paragraphs
          - [리뷰 서비스 안정화 및 성능 개선, pw: dhkim](https://kdohyeon.tistory.com/72)
          - JIRA 데이터 기반 업무 분석 
          - [명품 패션의 실 착용 정보를 제공하는 스타일 서비스 설계, 개발 및 분석](https://kdohyeon.tistory.com/74)
          - [상품 카탈로그 시스템 설계 및 개발](https://kdohyeon.tistory.com/76)
          - [CMS (컨텐츠 관리 시스템) 설계 및 개발](https://kdohyeon.tistory.com/75)

      - layout: left
        title: 쿠팡 (Coupang)
        sub_title: Backend Engineer
        caption: 2018. 08 ~ 2022. 03
        link: www.coupang.com
        quote: >
          이커머스 서비스
        description: | # this will include new lines to allow paragraphs
          - [통계 기반 상품의 이상 가격 탐지 서비스 설계 및 개발](https://kdohyeon.tistory.com/79)
          - [리테일 (로켓) 상품 카탈로그 관리 시스템 분석 및 개발](https://kdohyeon.tistory.com/78)
          - [대규모 서비스 분리](https://kdohyeon.tistory.com/77)
          - (2018. 10 ~ 2021. 10) 전문연구요원(병역 대체복무) 으로 3년 근무

  - title: 역량
    layout: text
    content:
      - layout: top-middle
        title: 신규 서비스, 비즈니스 개발
        description: |
          - [2022. 11 ~ 2022. 12 | 트렌비] [명품 패션의 실 착용 정보를 제공하는 스타일 탭 서비스 개발](https://kdohyeon.tistory.com/74)
          - [2022. 06 ~ 2022. 07 | 트렌비] 컨텐츠 관리 시스템 개발
          - [2022. 05 ~ 2022. 06 | 트렌비] 사이즈 리뷰 기능 개발
          - [2020. 01 ~ 2020. 03 | 쿠팡] 통계 기반 상품의 이상 가격 탐지 서비스 개발
          - [2019. 04 ~ 2019. 12 | 쿠팡] 리테일 (로켓) 상품 카탈로그 관리 백오피스 개발

      - layout: top-middle
        title: MSA 환경 개선 (서비스 분리 및 시스템 마이그레이션)
        description: |
          - [2018. 10 ~ 2019. 03 | 쿠팡] 리테일 (로켓) 상품 카탈로그 시스템 마이그레이션
          - [2020. 09 ~ 2020. 12 | 쿠팡] 리테일 (로켓) 상품 카탈로그 서비스 분리

      - layout: top-middle
        title: 데이터 구조 및 시스템 설계
        description: |
          - [2022. 07 ~ 2022. 11 | 트렌비] 상품 카탈로그 시스템 설계

      - layout: top-middle
        title: 성능 개선 및 시스템 안정화
        description: |
          - [2022. 05 | 트렌비] [리뷰 서비스 안정화 및 p90 API 응답 속도 250ms -> 30ms 개선](https://kdohyeon.tistory.com/72)

      - layout: top-middle
        title: 데이터 분석 사례
        description: |
          - [2023. 01 | 트렌비] 스타일 서비스 런칭 후 한달간의 데이터 분석
          - [2022. 12 | 트렌비] 올해 우리 팀은 어떻게 일 했나? JIRA 데이터 기반으로

  - title: 기술 스택
    layout: list
    content:
      - layout: left
        title: Backend
        description: | 
          - Java, Kotlin, Python
          - SpringBoot, SpringBatch, Spring Data, Spring Cloud AWS
          - JPA, QueryDSL
          - JUnit5, Spock
          - Gradle
          - IntelliJ
      - layout: left
        title: DevOps
        description: |
          - MySQL, PostgreSQL, Redis, ES
          - Jenkins, Github Action
          - Kafka
          - Git
      - layout: left
        title: Frontend
        description: |
          - JavaScript 
          - ReactJS

  - title: 학력
    layout: list
    content:
      - layout: top-left
        title: POSTECH
        sub_title: 산업경영공학 석사
        caption: 2016. 07 ~ 2018. 07
        link: https://aim.postech.ac.kr/
        link_text: 자세히 보기
        description: | # this will include new lines to allow paragraphs
          - 현대자동차, 삼성전자, 삼성중공업, 근로복지공단 등 다양한 산학 프로젝트 수행
          - 관심 연구 분야: 데이터 분석, 데이터 마이닝, 프로세스 마이닝
          - 졸업 논문: 프로세스 마이닝을 활용한 다각도 관점에서의 이상 (Anomaly) 탐지 방법 제안

      - layout: top-left
        title: UNIST
        sub_title: 컴퓨터 공학 학사, 기술 경영 학사
        caption: 2012. 03 ~ 2016. 02
        description: | # this will include new lines to allow paragraphs
          - 컴퓨터 공학 및 기술 경영 복수 전공

      - layout: top-left
        title: Hvitfeldtska Gymnasiet
        sub_title: 고등학교
        caption: 2008. 09 ~ 2011. 05
        description: | # this will include new lines to allow paragraphs
          - International Baccalaureate (IB) 졸업

  - title: 활동
    layout: list
    content:
      - layout: top-left
        title: 원데이 백엔드 클래스
        sub_title: 광운대학교
        caption: 2023. 01
        link: https://kdpark.notion.site/7fb8cd1a9c7b4412a4239087a10fd13d
        link_text: 자세히 보기
        description: |
          - 스프링부트 기반 백엔드 개발 시작하기
          - CRA (create-react-app) 기반 프론트엔드 개발 시작하기
          - 백엔드-프론트엔드 연동하기

      - layout: top-left
        title: 백엔드 온라인 강의
        sub_title: 코멘토
        caption: 2022. 11 ~ Present
        link: https://comento.kr/class/pt
        link_text: 자세히 보기
        quote: >
          Java & Spring 으로 클린아키텍처 기반 OpenAPI 백엔드시스템 개발하기
        description: |
          - 스프링 관련 핵심 개념 소개
          - 클린 아키텍쳐 및 프로젝트 환경 구성 소개
          - Spring JPA 소개
          - 테스트 작성의 중요성과 JUnit 기반 방법 소개
          - 1기. 2022년 11월, 2기. 2023년 1월

      - layout: top-left
        title: "쿠팡에서의 3년"
        sub_title: 광운대학교
        caption: 2021. 12
        link: https://www.instagram.com/p/CXX9RTqPook
        link_text: 자세히 보기
        description: |
          - 쿠팡에서의 주니어 백엔드 개발자로 겪은 시행착오, 경험에 대해 1시간동안 세미나 형식으로 진행

  - title: 수상/특허
    layout: list
    content:
      - layout: top-left
        title: 특허
        sub_title: 쿠팡
        caption: 2021. 04
        link: https://patents.google.com/patent/KR20220041800A/ko
        link_text: 자세히 보기
        description: |
          - 상품 판매 관리 정보를 제공하는 전자 장치 및 그 방법
          - 상품 가격의 이상 탐지를 위해 통계 기반 알고리즘 개발 및 발명

      - layout: top-left
        title: 수상
        sub_title: UNIST
        caption: 2015. 06
        description: |
          - Process Mining Case Competition. 3rd Prize Award
          - The 2015 Asia-Pacific Conference on Business Process Management Conference

  - title: 논문
    layout: list
    content:
      - layout: top-left
        title: 가상 버튼의 사용성 연구
        sub_title: POSTECH, 공저자
        caption: 2020. 03
        link: https://www.sciencedirect.com/science/article/abs/pii/S0169814119301052
        link_text: 자세히 보기
        description: |
          - Usability of the Size, Spacing, and Operation Method of Virtual Buttons with Virtual Hand on Head-Mounted Displays
          - International Journal of Industrial Ergonomics (SCIE)
          - Authors: Park, K., **Kim, D**., & Han, S.

      - layout: top-left
        title: LKAS 데이터 기반 이질감 계측 연구
        sub_title: POSTECH, 공저자
        caption: 2019. 05
        link: https://link.springer.com/article/10.1007/s12239-019-0043-6
        link_text: 자세히 보기
        description: |
          - Modelling the Intrusive Feelings of Advanced Driver Assistance Systems Based on Vehicle Activity Log Data: Case Study for the Lane Keeping Assistance System
          - International Journal of Automotive Technology (SCIE)
          - Authors: Park, K., Kwahk, J., Han, S., Song, M., Choi D., Jang, H., **Kim, D.**, Won, Y., & Jeong, I.

      - layout: top-left
        title: LKAS 데이터 기반 이질감 계측 연구
        sub_title: POSTECH, 공저자
        caption: 2018. 08
        link: https://jesk.or.kr/archive/articles/158
        link_text: 자세히 보기
        description: |
          - Measuring the Intrusive Feeling of a Lane Keeping Assistance System
          - Journal of the Ergonomics Society of Korea, 37(4), 459-473 (KCI)
          - Authors: Park, K., Kwahk, J., Han, S. H., Song, M., Choi, D. G., Jang, H., & **Kim, D**

      - layout: top-left
        title: 고용보험 실태조사 대상 선정 모델링
        sub_title: UNIST, 공저자
        caption: 2017. 12
        link: http://www.kbigdata.kr/bbs/board.php?bo_table=info02&wr_id=18
        link_text: 자세히 보기
        description: |
          - A Development on a Predictive Model for Buying Unemployment Insurance Program Based on Public Data
          - The Korean Journal of BigData, 2(2), 17-31 (KCI)
          - Cho, M., **Kim, D.**, Song, M., Kim, G., Jung, C., & Kim, K.

  - title: 연구 경험
    layout: list
    content:
      - layout: top-left
        title: 이상 탐지 알고리즘 연구
        sub_title: POSTECH, 참여연구원
        caption: 2018. 03 ~ 2018. 06
        quote: >
          [삼성중공업] 공정 로그 데이터 기반 이상 공정 탐지 알고리즘 개발
        description: |
          - 공정 로그 데이터 구조 파악 및 이상 공정 탐지 알고리즘 개발

      - layout: top-left
        title: 데이터 기반 서비스 경험 산학 연구
        sub_title: POSTECH, 참여연구원
        caption: 2017. 12 ~ 2018. 04
        quote: >
          [삼성전자] DATA 기반 INTELLIGENCE 서비스 경험 산학 연구
        description: |
          - 데이터 기반 서비스 경험 개선 시나리오 구현 가능성 검토
          - 샘플 데이터 기반의 포로토타입 프로그램 개발 (Python)

      - layout: top-left
        title: 시스템 로그 및 UX 분석 모델 연구
        sub_title: POSTECH, 참여연구원
        caption: 2017. 07 ~ 2017. 11
        quote: >
          [삼성중공업] 프로세스 마이닝 기반 시스템 로그 및 UX 분석 모델 개발
        description: |
          - 프로세스 마이닝 분석을 위해 데이터 및 UX 요구사항 분석
          - 데이터 파악을 위해 EDA 수행 및 분석을 위한 데이터 전처리
          - UI (화면), 부서, 사용자, 시간 관점에서 다각도 데이터 분석 수행

      - layout: top-left
        title: IoT Intelligence 서비스 경험 연구
        sub_title: POSTECH, 참여연구원
        caption: 2017. 05 ~ 2017. 09
        quote: >
          [삼성전자] Multi-device / Multi-source data 기반 IoT Intelligence 서비스 경험 연구
        description: |
          - 삼성 커넥트 서비스의 편의성 및 품질 향상을 위해 서비스 경험 및 컨셉 디자인
          - 서비스 경험을 개선하기 위해 필요한 데이터 파악 및 프로세스 정의

      - layout: top-left
        title: LKAS 데이터 분석
        sub_title: POSTECH, 참여연구원
        caption: 2016. 05 ~ 2017. 07
        quote: >
          [현대자동차] LKAS 데이터 통계 분석 및 RATING 프로그램 개발
        description: |
          - LKA 성능 지표 및 통합 점수 산출 방법 개발 등 성능 분석 방법론 개발
          - 분석 시스템 요구사항 분석 및 Java 기반 LKA 성능 분석 자동화 시스템 개발

      - layout: top-left
        title: 대용량 데이터 기반 모델링 연구
        sub_title: UNIST, 참여연구원
        caption: 2016. 05 ~ 2016. 08
        link: https://kdohyeon.tistory.com/70
        link_text: > 
          자세히 보기 (pw: dhkim)
        quote: >
          [근로복지공단] 대용량 데이터를 활용한 산재 및 고용보험 가입누락 조사대상 사업장 구축
        description: |
          - 사업장 관련 데이터 전처리 및 데이터 통합
          - 의사결정나무 기반 모델링

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
